### ISSUE TITLE
Add Ada Chautal

### ISSUE THREAD

**Issue by cFlour** [Studio-kalavati/bandish-editor#88]
Please add the taal of Ada Chautal:
| धिं तिरकिट | धिं ना | तू ना | कत् ता | तिरकिट धिं | ना धिं | धिं ना |
|------------|------|------|--------|------------|------|-------|
| x               | 2      | o     | 3         | o              | 4      | o       |

**Comment by shark8me** [comment]
hi @cFlour,

If you are familiar with the process of creating a PR, please create one in this project.
Here's an example of the [format for Jhaptaal](https://github.com/Studio-kalavati/sargam-spec/blob/master/src/sargam/talas.cljc#L15) and [a description](https://github.com/Studio-kalavati/sargam-spec/tree/master#taal-definition)

**Comment by RajarshiRit** [comment]
For Bengali input Arha Chautaal ,
 use " আড়া চৌতাল " ।

**Comment by cFlour** [comment]
@shark8me okay I have made [this pull request](https://github.com/Studio-kalavati/sargam-spec/pull/11).

Won't that would only update the khands for the taal? There are also tabla sounds which play in the app, any idea how to add those?

**Comment by shark8me** [comment]
Thanks, I've merged the PR and added display support for the same here.

Yup, you are right that the sounds are added separately. Here's an [example](https://github.com/Studio-kalavati/bandish-editor/tree/main/resources/public/sounds/tabla/teentaal) of what's required (for another Taal, Teentaal).

Basically since each Taal has more strokes at slower speed and fewer strokes at a higher speed, it needs a separate mp3 file for each speed from 60bpm to 300bpm (in increments of 15). The tabla is tuned to the key of C.

If you have such files, please do share it. Otherwise the playback would be limited to a metronome which makes a sound at the start of each Bhaag.

@RajarshiRit Please see attached Taal description in Bangla
![taal_in_bangla](https://github.com/Studio-kalavati/bandish-editor/assets/89076/05cd6039-7e5d-4218-9eb5-d33990b84081)

**Comment by cFlour** [comment]
I don't have any such files on record yet, but I will try to find them.

**Comment by shark8me** [comment]
Thanks, I'll take a look.

**Comment by shark8me** [comment]
@cFlour The audio for Ada Chautaal is now available, let us know how it sounds.

**Comment by cFlour** [comment]
@shark8me I checked at all BPMs from 60-240 and it is working perfectly. Thank you for adding this!
